### ISSUE TITLE
Make streams-explorer configuration in Helm chart easier

### ISSUE THREAD

**Issue by VictorKuenstler** [bakdata/streams-explorer#123]
Add extra section for config:
```yaml
config:
  KAFKACONNECT_url: http://localhost:8083
  KAFKACONNECT_url: http://localhost:8083
```
The corresponding environment variables with the `SE_` prefix are generated then.

Additionally, we could provide `.Values.settings` that allow passing the whole `settings.yaml`  as a string. The helm chart then creates a ConfigMap ( with the `settings.yaml` as content) that is mounted as a volume to the chart.
