### ISSUE TITLE
Support for statefulsets, potentially configmaps for discovery 

### ISSUE THREAD

**Issue by twiechert** [bakdata/streams-explorer#80]
It is common for kstream apps to run as statefulsets. It seems, however, streams-explorer is currently limited to deployment and cronjob-based discovery.

I thus propose to add support for statefulsets and ideally even configmaps for discovery.

**Comment by VictorKuenstler** [comment]
Hi @twiechert ,
thanks for your proposal. We are currently not using statefulsets and configmaps for our streaming applications. Could you please provide an example configuration of a configmap and a statefulset that should be discovered?

**Comment by twiechert** [comment]
Hi @VictorKuenstler 

the discovery of the sts would work just like the one for deployments. It would be looking for the pipeline label and extract the topology from the env variables attached to the sts spec.
 

The configmap based approach would simply decouple the topology description from the deployment mechanism (deployment vs statefulset vs cronjob).

Similarly, a configmap as topology descriptor would carry the same label for discovery and contain as data items the required topology config items:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-fancy-pipeline-descriptor
  annotations:
    cgroup: kstream-001
  labels:
    pipeline: fancy-pipeline
data:
  INPUT_TOPICS: bla
  EXTRA_INPUT_TOPICS: bla

```
