### ISSUE TITLE
Helm chart - rbac objects should iterate over SE_K8S__deployment__namespaces

### ISSUE THREAD

**Issue by twiechert** [bakdata/streams-explorer#82]
The namespaced rbac resources should be decoupled from the deployment namespace of the streams-explorer.
For example, in our cluster, we deploy streams-explorer in _infra_ and plan to discover stream apps in _data_ and _app_.

I feel this is a valid use case and should be supported by the helm chart:

**Proposal:**

- Role becomes a ClusterRole
- a **RoleBinding** from CR to SA is created on a per namespace basis.
- this effectively binds the CR to the target namespaces.
- this can be made optional by introducing 

```
rbac:
  enabled: true
  clusterScope:
     enabled: true
     namespaces: ["apps", "data"]
```
